apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-vsbm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-vsbm
    app.kubernetes.io/part-of: tkrw-pr712-0075-0055-app
  name: devfile-sample-vsbm
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-vsbm
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-vsbm
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0055-tenant/tkrw-pr712-0075-0055-app/devfile-sample-vsbm@sha256:00dc8657a67ed8b3ed75ea24e04d8ce6bd6257a25f7e568ec6d6c4b42ec89792
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
